/* generated by unplugin-react-components */
export {}
declare global{
	const Web3ModalProvider: typeof import('./src/context/web3')['default']
	const Button: typeof import('./src/stories/Button')['Button']
	const Page: typeof import('./src/stories/Page')['Page']
}