/* generated by unplugin-react-components */
export {}
declare global{
	const NavbarAccount: typeof import('./src/components/NavbarAccount')['default']
	const WagmiHooks: typeof import('./src/components/WagmiHooks')['WagmiHooks']
	const Web3ModalProvider: typeof import('./src/context/web3')['default']
	const Button: typeof import('./src/stories/Button')['Button']
	const Page: typeof import('./src/stories/Page')['Page']
	const Default: typeof import('./src/stories/Components/AvatarEdit.stories')['Default']
	const Custom: typeof import('./src/stories/Components/AvatarOverlayEdit.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/BaseCalendar.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/InputDate.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/MessageWarningFlagged.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/ModalSelectDate.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/SpaceCreateVotingDateStart.stories')['Custom']
	const Custom: typeof import('./src/stories/Components/UiInput.stories')['Custom']
}